/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Combinators: typeof import('@sinclair/parsebox').Runtime
  const P: typeof import('ts-pattern').P
  const at: typeof import('es-toolkit/array').at
  const chunk: typeof import('es-toolkit/array').chunk
  const compact: typeof import('es-toolkit/array').compact
  const countBy: typeof import('es-toolkit/array').countBy
  const difference: typeof import('es-toolkit/array').difference
  const differenceBy: typeof import('es-toolkit/array').differenceBy
  const differenceWith: typeof import('es-toolkit/array').differenceWith
  const drop: typeof import('es-toolkit/array').drop
  const dropRight: typeof import('es-toolkit/array').dropRight
  const dropRightWhile: typeof import('es-toolkit/array').dropRightWhile
  const dropWhile: typeof import('es-toolkit/array').dropWhile
  const fill: typeof import('es-toolkit/array').fill
  const flatMap: typeof import('es-toolkit/array').flatMap
  const flatMapDeep: typeof import('es-toolkit/array').flatMapDeep
  const flatten: typeof import('es-toolkit/array').flatten
  const flattenDeep: typeof import('es-toolkit/array').flattenDeep
  const flow: typeof import('es-toolkit/function').flow
  const flowRight: typeof import('es-toolkit/function').flowRight
  const groupBy: typeof import('es-toolkit/array').groupBy
  const head: typeof import('es-toolkit/array').head
  const initial: typeof import('es-toolkit/array').initial
  const intersection: typeof import('es-toolkit/array').intersection
  const intersectionBy: typeof import('es-toolkit/array').intersectionBy
  const intersectionWith: typeof import('es-toolkit/array').intersectionWith
  const isSubset: typeof import('es-toolkit/array').isSubset
  const isSubsetWith: typeof import('es-toolkit/array').isSubsetWith
  const keyBy: typeof import('es-toolkit/array').keyBy
  const last: typeof import('es-toolkit/array').last
  const match: typeof import('ts-pattern').match
  const maxBy: typeof import('es-toolkit/array').maxBy
  const minBy: typeof import('es-toolkit/array').minBy
  const orderBy: typeof import('es-toolkit/array').orderBy
  const partial: typeof import('es-toolkit/function').partial
  const partialRight: typeof import('es-toolkit/function').partialRight
  const partition: typeof import('es-toolkit/array').partition
  const pull: typeof import('es-toolkit/array').pull
  const pullAt: typeof import('es-toolkit/array').pullAt
  const remove: typeof import('es-toolkit/array').remove
  const rest: typeof import('es-toolkit/function').rest
  const sample: typeof import('es-toolkit/array').sample
  const sampleSize: typeof import('es-toolkit/array').sampleSize
  const shuffle: typeof import('es-toolkit/array').shuffle
  const sortBy: typeof import('es-toolkit/array').sortBy
  const spread: typeof import('es-toolkit/function').spread
  const tail: typeof import('es-toolkit/array').tail
  const take: typeof import('es-toolkit/array').take
  const takeRight: typeof import('es-toolkit/array').takeRight
  const takeRightWhile: typeof import('es-toolkit/array').takeRightWhile
  const takeWhile: typeof import('es-toolkit/array').takeWhile
  const toFilled: typeof import('es-toolkit/array').toFilled
  const union: typeof import('es-toolkit/array').union
  const unionBy: typeof import('es-toolkit/array').unionBy
  const unionWith: typeof import('es-toolkit/array').unionWith
  const uniq: typeof import('es-toolkit/array').uniq
  const uniqBy: typeof import('es-toolkit/array').uniqBy
  const uniqWith: typeof import('es-toolkit/array').uniqWith
  const unzip: typeof import('es-toolkit/array').unzip
  const unzipWith: typeof import('es-toolkit/array').unzipWith
  const windowed: typeof import('es-toolkit/array').windowed
  const without: typeof import('es-toolkit/array').without
  const xor: typeof import('es-toolkit/array').xor
  const xorBy: typeof import('es-toolkit/array').xorBy
  const xorWith: typeof import('es-toolkit/array').xorWith
  const zip: typeof import('es-toolkit/array').zip
  const zipObject: typeof import('es-toolkit/array').zipObject
  const zipWith: typeof import('es-toolkit/array').zipWith
}
