import autoImport from "unplugin-auto-import";
import { defineConfig } from "tsdown";

export default defineConfig({
  exports: true,
  plugins: [
    autoImport.rolldown({
      imports: [
        {
          from: "ts-pattern",
          imports: ["match", "P"],
        },
        {
          from: "@sinclair/parsebox",
          imports: [["Runtime", "Combinators"]],
        },
        {
          from: "es-toolkit/array",
          imports: [
            "at",
            "chunk",
            "compact",
            "countBy",
            "difference",
            "differenceBy",
            "differenceWith",
            "drop",
            "dropRight",
            "dropRightWhile",
            "dropWhile",
            "fill",
            "flatMap",
            "flatMapDeep",
            "flatten",
            "flattenDeep",
            "groupBy",
            "head",
            "initial",
            "intersection",
            "intersectionBy",
            "intersectionWith",
            "isSubset",
            "isSubsetWith",
            "keyBy",
            "last",
            "maxBy",
            "minBy",
            "orderBy",
            "partition",
            "pull",
            "pullAt",
            "remove",
            "sample",
            "sampleSize",
            "shuffle",
            "sortBy",
            "tail",
            "take",
            "takeRight",
            "takeRightWhile",
            "takeWhile",
            "toFilled",
            "union",
            "unionBy",
            "unionWith",
            "uniq",
            "uniqBy",
            "uniqWith",
            "unzip",
            "unzipWith",
            "windowed",
            "without",
            "xor",
            "xorBy",
            "xorWith",
            "zip",
            "zipObject",
            "zipWith",
          ],
        },
        {
          from: "es-toolkit/function",
          imports: [
            "flow",
            "flowRight",
            "partial",
            "partialRight",
            "rest",
            "spread",
          ],
        },
      ],
    }),
  ],
  // ...config options
});
